export const projects = [
  {
    id: 1,
    title: "Deved Up",
    descriptionKey: "projects.items.1.description",
    image: "/projects/deved-up.png",
    tags: "Next.js App Route, TailwindCss, Swiper, MUI, i18n, Responsive Design",
    demoUrl: "https://deved-up.com",
    inDev: false,
  },
  {
    id: 2,
    title: "The General Authority for Tourism and Hotel Training in Syria.",
    descriptionKey: "projects.items.2.description",
    image: "/projects/tourism.png",
    tags: "Next.js App Route, TailwindCss , Swiper , Responsive Design",
    demoUrl: "https://gc-tht.edu.sy/",
    inDev: false,
  },
  {
    id: 3,
    title: "Cinpaa Training",
    descriptionKey: "projects.items.3.description",
    image: "/projects/cinpaa.png",
    tags: "React, TailwindCSS, Axios, i18next",
    demoUrl: "http://front-end.cinpaa.org/",
    inDev: false,
  },
  {
    id: 4,
    title: "Ecotransferz Admin Panel",
    descriptionKey: "projects.items.4.description",
    image: "/projects/eco.png",
    tags: "react, react-router-dom, react-query, custom hook, firebase notification, signalR, MUI, tailwindCss",
    inDev: false,
  },
  {
    id: 5,
    title: "POS Open Spark (SaaS System)",
    descriptionKey: "projects.items.5.description",
    image: "/projects/pos.png",
    tags: "React, react-router, typeScript, axios, open api generator, oidc oAuth2, MUI, tailwindCss",
    inDev: true,
  },

  {
    id: 9,
    title: "Tranplus Admin Panel",
    descriptionKey: "projects.items.9.description",
    image: "/projects/transplus.png",
    tags: "React, react-router, typeScript, redux-toolkit",
    inDev: false,
  },
  {
    id: 10,
    title: "Inventory Management",
    descriptionKey: "projects.items.10.description",
    image: "/projects/inventory.png",
    tags: "Next.js ,Typescript ,  PostgreSQL , Prisma , TailwindCss , Stack Auth",
    demoUrl: "https://inventory-app-jade.vercel.app/",
    inDev: false,
  },
  {
    id: 11,
    title: "job-tracker",
    descriptionKey: "projects.items.11.description",
    image: "/projects/job-tracker.png",
    tags: "Next.js , MongoDB, Mongoose ODM , TailwindCss , Shadcn UI , Dnd Kit , Better Auth",
    demoUrl: "https://job-tracker-wine-nu.vercel.app/",
    inDev: false,
  },
];
